services:
  tts-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ESPNET_TTS_ESPEAK_NG_DICT_DIR=/tmp/espeak-ng-data
    volumes:
      # Opcional: mount para persistir modelos baixados
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge
